In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("gdpr_privacyci.csv")

In [4]:
df.head()

,norm_type,sender,sender_role,recipient,recipient_role,subject,subject_role,information_type,consent_form,purpose,followed_articles,violated_articles,case_content
0,prohibit,['Meta Platforms Ireland Limited'],['Data Controller'],['Internal Systems'],['Data Storage'],['Users'],['Data Subjects'],['Passwords'],NaN,Data Storage,[],['Article 32' 'Article 33' 'Article 34'],Meta Platforms Ireland Limited (MPIL) stored u...
1,prohibit,"['LOCAL VERTICALS, S.L.']",['Data Controller'],['Third-party company'],['Data Processor'],['Individual'],['Data Subject'],['Privacy Policy Information'],NaN,Providing information about data processing,[],['Article 12' 'Article 13'],An individual attempted to register on the web...
2,prohibit,"['SANTANDER CONSUMER FINANCE, S.A.']",['Company'],['Individual'],['Customer'],['Individual'],['Customer'],['Personal Data'],Authorization,Managing Credit Card,[],['Article 6 - Lawfulness of processing'\n 'Art...,"An individual, who is a customer of SANTANDER ..."
3,prohibit,['University of Agder'],['Data Controller'],['Employees with no business need'],['Unauthorized Accessors'],['Employees' 'Students' 'External Individuals'],['Data Subjects'],['Personal Data'],NaN,NaN,[],['Article 5(1)(f)' 'Article 32'],The University of Agder (UiA) stored documents...
4,prohibit,['mBank employee'],['Bank Employee'],['Wrong recipient'],['Unintended Recipient'],['mBank customers'],['Bank Customer'],['Names' 'Account numbers' 'Dates of birth' 'I...,Authorization,Banking operations,[],['Article 33' 'Article 34'],An employee of mBank mistakenly sent documents...

In [8]:

sampled_df = df.groupby('norm_type', group_keys=False).apply(lambda x: x.sample(n=50, random_state=42))


sample_df

1407    prohibit
2253    prohibit
2866      permit
2841      permit
1652    prohibit
          ...
99      prohibit
2426    prohibit
2990      permit
839     prohibit
1385    prohibit
Name: norm_type, Length: 100, dtype: str

In [9]:
sampled_df = df.groupby('norm_type').sample(n=50, random_state=1)
sampled_df

,norm_type,sender,sender_role,recipient,recipient_role,subject,subject_role,information_type,consent_form,purpose,followed_articles,violated_articles,case_content
2554,permit,['Google'],['Service Provider'],['Google' 'Advertising Partners'],['Service Provider' 'Advertisers'],['Alex Johnson' 'Customers'],['User' 'Customer'],['Website Interaction Data' 'Ad Preferences'],Consent,Service Enhancement and Targeted Advertising,['Article 6 - Lawfulness of processing'\n 'Art...,[],Alex Johnson's use of Google Sites and subsequ...
2610,permit,['Google'],['Service Provider'],['Google'],['Data Controller'],['Alex'],['User'],['Browsing Behavior' 'Language Preferences'],Consent,Enhancing User Experience and Tailored Adverti...,['Article 6 - Lawfulness of processing'\n 'Art...,[],"In 2023, a user named Alex reported concerns a..."
2621,permit,['InnovateX'],['Tech Startup'],['Google'],['Data Controller'],['Users'],['Data Subjects'],['User Data'],Authorization,Enhancing AI-driven marketing platform,['Article 6 - Lawfulness of processing'\n 'Art...,[],InnovateX approached Google to access user dat...
2922,permit,['Alex'],['User'],['Bing'],['Service Provider'],['Alex'],['User'],['Language Preferences'],NaN,Enhancing User Experience,['Article 6 - Lawfulness of processing'\n 'Art...,[],Alex configured their browser to block all coo...
2915,permit,['Google'],['Service Provider'],['Alex'],['User'],['Alex'],['User'],['Correspondence Record' 'Service Update Infor...,NaN,"Issue Resolution, Service Update Notification",['Article 6(1)(b)' 'Article 6(1)(f)'],[],"In early 2023, a user named Alex contacted Goo..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1071,prohibit,['Employee'],['Employee at Covid testing center'],['Test subject'],['Individual'],['Test subject'],['Individual'],['Phone number'],Authorization,Private contact,[],['Article 5(1)(b)' 'Article 6(1)'],An employee working at a Covid testing center ...
1641,prohibit,['Malagatrom S.L.U.'],['Controller'],['Public'],['General Public'],['Data Subject'],['Customer'],['First Name' 'Last Name' 'Address' 'Cell Phon...,NaN,NaN,[],['Article 5(1)(a)' 'Article 6(1)' 'Article 9(1)'],A data subject purchased a product from Malaga...
1045,prohibit,"['Meta Platforms, Inc.']",['Data Controller'],['Public'],['Data Recipient'],['Minors using Instagram'],['Data Subject'],['Cell phone numbers' 'Email addresses' 'Socia...,Authorization,Social media interaction,[],['Article 5(1)(a)' 'Article 5(1)(c)' 'Article ...,"Meta Platforms, Inc. operated Instagram, a soc..."
75,prohibit,"[""Homeowners' association""]",['Data Controller'],['Public'],['None'],['Individuals in public space'],['Data Subject'],['Video surveillance footage'],Authorization,Security,[],['Article 5(1)(c) - Data Minimization'\n 'Arti...,A Homeowners' association installed video surv...
975,prohibit,['Intesa Sanpaolo Vita S.p.a.' 'employee'],['insurance company' 'employee'],['third parties'],['unknown'],['data subject'],['policyholder'],['first name' 'last name' 'information about t...,Authorization,NaN,[],['Article 5(1)(f)' 'Article 6(1)'],A data subject took out a life insurance polic...

In [14]:
sampled_df.to_csv("privacyci_gdpr.csv", index=False)